### ISSUE TITLE
October should handle malformed config.json instead of failing to start up

### ISSUE THREAD

**Issue by 0xt41ch1** [marcus-crane/october#98] opened 2023-11-04 03:19 UTC
I have been using the October app for syncing my Kobo reader highlights to Readwise. It used to work perfectly on my Mac. But recently, after upgrading my macOS to the latest version, Sonoma, I am unable to open the app.
Here are the details of my system:
	•	macOS version: Apple M1 Pro Sonoma 14.1 (23B74)
	•	October app version: v1.6.0
The app either crashes upon opening or doesn't open at all. I tried re-installing the app but the issue persists. Any help resolving this would be greatly appreciated.

**Comment by marcus-crane** [comment] 2023-11-05 21:59
Hey @0xt41ch1,

Ah, that's quite surprising to hear! I have an M1 Pro myself although it's running 14.0 (23A339) so I'll try upgrading it and see if I can replicate what you're seeing.

In the meantime, you can find logs for October by opening Finder and navigating to `Go -> Go to Folder` and then entering `/Users/<username>/Library/Application Support/October/logs`.

If you can email me the most recent logs (or just zip up the whole folder if that's easier) to `october@utf9k.net`, it'll help me get an idea of what might be going on.

Thanks

**Comment by 0xt41ch1** [comment] 2023-11-06 08:20
After time of debugging, I noticed an extra bracket in the config.json file within the Logs folder. For clarity, I had never modified this file before. However, removing (or renaming) the config.json file enabled me to open the app again successfully, pointing towards a malformed JSON file.

`
{
	"readwise_token": "xxxx",
	"upload_covers": true,
	"upload_store_highlights": true,
	"upload_store_prompt_shown": true
}}

`

**Comment by marcus-crane** [comment] 2023-11-06 08:23
Hey @0xt41ch1,

Ah, interesting! I'm glad that you resolved your issue. It sounds like October should try to be a bit smarter then so if it fails to load up, it at least resets the JSON config to something valid.

**Comment by marcus-crane** [comment] 2023-11-16 01:51
Looks like another possible case of this: https://github.com/marcus-crane/october/discussions/99

I'll try and look into this bug shortly

**Comment by marcus-crane** [comment] 2023-11-16 05:50
Confirming that I've managed to replicate the original bug with the latest release, although only when the config file is freshly created it seems.

If you have an existing configuration file, it appears to update the file just fine interestingly enough.

**Comment by marcus-crane** [comment] 2023-11-16 06:02
Seems to be specifically caused by enabling and then disabling the toggle for store bought books

**Comment by marcus-crane** [comment] 2023-11-16 06:11
Ah ok, it looks like a race condition where because the "Upload store bought books" toggles (and saved) the file twice in one go, there's a chance that the file will get mangled.

For now, I'll do a patch release to remove the dual updating but it should be handled a bit better to avoid this stuff

**Comment by marcus-crane** [comment] 2023-12-06 08:28
Marking this as fixed, as the bug was resolved in v1.7.0 as well as a small patch to try and fix any corrupted settings files discovered.

https://github.com/marcus-crane/october/releases/tag/v1.7.0

**Closed by marcus-crane** 2023-12-06 08:28 UTC
Labels: bug
