### ISSUE TITLE
Location of synced highlights

### ISSUE THREAD

**Issue by KoboCowboy** [marcus-crane/october#77] opened 2023-02-10 14:46 UTC
Hi, thanks for October. The issue I have is that my highlights imported to readwise are completely out of order, there is no location data. Fine if there is no clickable link but just having them in order would be good. When I go onto my Kobo reader and have a look at the highlights and sort by location then they appear in order but their import order to Readwise seems to be random. Is there any way to add location data or order to the highlights? 
---

<details><summary>System Details</summary><ul><li>Version: v1.3.1</li><li>Platform: darwin</li><li>Architecture: arm64</li></details>

**Comment by marcus-crane** [comment] 2023-02-17 09:36
Closing this as it's a duplicate of https://github.com/marcus-crane/october/issues/46 which I think you've already noticed

**Closed** 2023-02-17 09:44 UTC
